### ISSUE TITLE
Add yfinance helper functions

### ISSUE THREAD

**Issue by MattGeimer** [CS196Illinois/Finance#35]
- getCurrentPrice(String: stockTicker)
- getHistoricalPrice(String: stockTicker)

**Comment by MattGeimer** [comment]
@YZY000403 Can you comment w/ an update on this?

**Comment by YZY000403** [comment]
kind of finished, but still have questions

**Comment by MattGeimer** [comment]
@YZY000403 Make sure this is pulled to the master so the details page can use the helpers.
