### ISSUE TITLE
Yours/Watching page

### ISSUE THREAD

**Issue by MattGeimer** [CS196Illinois/Finance#38]
Meet sometime this week and come up with a unified look for the page. Then, implement it.
Please make sure to have the data that the page shows be modular (such that when the JSON guys are done with the getter function, it's not a pain to swap real data in).

Also, feel free to pair program (have one person screen share what they're doing). It's actually fairly efficient. (Note that if you do this, just make a not of it in the pull request and only commit to one of your branches)

**Comment by MattGeimer** [comment]
The yours page and the watching page should be identical. The only difference will be the number of stocks within the list.

Try to have a finished page by the end of this week. It should include ([] are for the different versions): 

- list of stocks you [could buy]/[currently own]
- A button that, when clicked, opens up a new window (the stock detail page
- A back button to the home page

Until @coolestinCS125 and @PatinaShi614 have finished the stock detail page, just have it open up a placeholder window with a label containing the ticker of the stock you chose.

**Comment by YZY000403** [comment]
kewei and I were working on how to make both of our codes run one person's computer

**Comment by MattGeimer** [comment]
@arahim2 Help out @YZY000403 and @skwa-KeweiSong finish this page. We really need it to be done by the end of this week, so if you three could meet 2-3 times this week to wrap it up, that would be helpful.
